### ISSUE TITLE
Z offset is only 6mm taller than standard revo

### ISSUE THREAD

**Issue by ecgraffcam** [keyquesttech/Rtv6#1]
You describe the adapter as being 13mm taller than a standard Revo nozzle. It is only 6mm taller. 
Starting after the heat block the adapter + a v6 nozzle are 13mm tall and a standard revo nozzle is 7mm tall.

**Comment by keyquesttech** [comment]
You're absolutely right. I was counting from the bottom of the stock mini afterburner.
